# List available recipes
default:
    @just --list

# Build docker image
build:
  docker build -f Dockerfile -t jolt:hash .

# Archive docker image
save:
  docker save jolt:hash | gzip > jolt_hash.tar.gz

hash:
  fermah-seek util hash jolt_hash.tar.gz

prove:
  docker run -it --rm \
    -v /tmp/fermah-proofs:/proofs \
    -e "FILE_LOCATION=" \
    -e "PROOF_LOCATION=/proofs/proof.bin" \
    -v file.txt:/input/file.txt \
    --entrypoint "/app/prove"
    jolt:hash

verify:
  docker run -it --rm \
    -v /tmp/fermah-proofs:/proofs \
    -e "PROOF_LOCATION=/proofs/proof.bin" \
    --entrypoint "/app/verify"
    jolt:hash

send_proof:
  cargo run -p fermah-seek -- proof send -k dev \
    -n jolt_hash \
    --rpc ws://devnet.fermah.xyz:8080  \
    --key seeker